/*
  File autogenerated by gengetopt version 2.22
  generated with the following command:
  gengetopt -i fastdist.ggo --file-name=fastdist_gengetopt --unamed-opts=FILE

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "fastdist_gengetopt.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: fastdist [OPTIONS]... [FILE]...";

const char *gengetopt_args_info_description = "Computes distance matrices out of multialignments";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "If FILE is not specified the input is read from stdin ",
  "  -o, --outfile=filename        output filename. If not specifed, output is \n                                  written to stdout",
  "  -I, --input-format=ENUM       input format  (possible \n                                  values=\"phylip_multialignment\", \"xml\" \n                                  default=`phylip_multialignment')",
  "  -O, --output-format=ENUM      output format  (possible values=\"phylip_dm\", \n                                  \"xml\" default=`phylip_dm')",
  "  -D, --distance-function=ENUM  Distance function  (possible values=\"JC\", \n                                  \"K2P\", \"FAKE_F84\", \"TN93\", \"HAMMING\" \n                                  default=`K2P')",
  "  -b, --bootstraps=INT          Bootstrap num times and create matrix for each  \n                                  (default=`0')",
  "  -k, --no-incl-orig            If the distance matrix from the original \n                                  sequences should be included  (default=off)",
  "  -s, --seed=INT                Random seed. If not specified the current \n                                  timestamp will be used",
  "  -A, --no-ambiguities          Ignore ambiguities  (default=off)",
  "  -R, --no-ambig-resolve        Specifies that ambigious symbols should not be \n                                  resolved by nearest neighbor  (default=off)",
  "  -t, --no-transprob            Specifies that the transition probabilities \n                                  should not be used in the ambiguity model  \n                                  (default=off)",
  "  -a, --ambiguity-frequency-model=ENUM\n                                Ambiguity frequency model  (possible \n                                  values=\"UNI\", \"BASE\" default=`UNI')",
  "  -T, --tstvratio=FLOAT         Transition/transvertion ratio for purine \n                                  transitions ( for the TN model )  \n                                  (default=`2.0')",
  "  -P, --pyrtvratio=FLOAT        Transition/transvertion ratio for  pyrimidines \n                                  transitions ( for the TN model )  \n                                  (default=`2.0')",
  "  -N, --no-tstvratio            If given fixed ts/tv ratios will not be used  \n                                  (default=off)",
  "  -F, --fixfactor=FLOAT         Float specifying what factor to use for \n                                  saturated data. If not given -1 in the entry. \n                                   (default=`1')",
  "  -d, --datasets=INT            nr of datasets in input. Is used if the input \n                                  format is clustalw  (default=`1')",
  "Options for tree building:",
  "  -C, --no-counts               Tree file should not contain the counts  \n                                  (default=off)",
  "  -m, --method=ENUM             reconstruction method to apply  (possible \n                                  values=\"NJ\", \"FNJ\", \"BIONJ\")",
  "Example usage: \n$ ./fastdist infile.seq\n$ ./fastdist -D JC -o outfile.txt infile.seq \n\nCreates 10 bootstrapped matrices \n$./fastdist -o outfile.txt -b 10 --no-incl-orig infile.seq \n",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

char *cmdline_parser_input_format_values[] = {"phylip_multialignment", "xml", 0} ;	/* Possible values for input-format.  */
char *cmdline_parser_output_format_values[] = {"phylip_dm", "xml", 0} ;	/* Possible values for output-format.  */
char *cmdline_parser_distance_function_values[] = {"JC", "K2P", "FAKE_F84", "TN93", "HAMMING", 0} ;	/* Possible values for distance-function.  */
char *cmdline_parser_ambiguity_frequency_model_values[] = {"UNI", "BASE", 0} ;	/* Possible values for ambiguity-frequency-model.  */
char *cmdline_parser_method_values[] = {"NJ", "FNJ", "BIONJ", 0} ;	/* Possible values for method.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->outfile_given = 0 ;
  args_info->input_format_given = 0 ;
  args_info->output_format_given = 0 ;
  args_info->distance_function_given = 0 ;
  args_info->bootstraps_given = 0 ;
  args_info->no_incl_orig_given = 0 ;
  args_info->seed_given = 0 ;
  args_info->no_ambiguities_given = 0 ;
  args_info->no_ambig_resolve_given = 0 ;
  args_info->no_transprob_given = 0 ;
  args_info->ambiguity_frequency_model_given = 0 ;
  args_info->tstvratio_given = 0 ;
  args_info->pyrtvratio_given = 0 ;
  args_info->no_tstvratio_given = 0 ;
  args_info->fixfactor_given = 0 ;
  args_info->datasets_given = 0 ;
  args_info->no_counts_given = 0 ;
  args_info->method_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->outfile_arg = NULL;
  args_info->outfile_orig = NULL;
  args_info->input_format_arg = input_format_arg_phylip_multialignment;
  args_info->input_format_orig = NULL;
  args_info->output_format_arg = output_format_arg_phylip_dm;
  args_info->output_format_orig = NULL;
  args_info->distance_function_arg = distance_function_arg_K2P;
  args_info->distance_function_orig = NULL;
  args_info->bootstraps_arg = 0;
  args_info->bootstraps_orig = NULL;
  args_info->no_incl_orig_flag = 0;
  args_info->seed_orig = NULL;
  args_info->no_ambiguities_flag = 0;
  args_info->no_ambig_resolve_flag = 0;
  args_info->no_transprob_flag = 0;
  args_info->ambiguity_frequency_model_arg = ambiguity_frequency_model_arg_UNI;
  args_info->ambiguity_frequency_model_orig = NULL;
  args_info->tstvratio_arg = 2.0;
  args_info->tstvratio_orig = NULL;
  args_info->pyrtvratio_arg = 2.0;
  args_info->pyrtvratio_orig = NULL;
  args_info->no_tstvratio_flag = 0;
  args_info->fixfactor_arg = 1;
  args_info->fixfactor_orig = NULL;
  args_info->datasets_arg = 1;
  args_info->datasets_orig = NULL;
  args_info->no_counts_flag = 0;
  args_info->method_arg = NULL;
  args_info->method_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->outfile_help = gengetopt_args_info_help[3] ;
  args_info->input_format_help = gengetopt_args_info_help[4] ;
  args_info->output_format_help = gengetopt_args_info_help[5] ;
  args_info->distance_function_help = gengetopt_args_info_help[6] ;
  args_info->bootstraps_help = gengetopt_args_info_help[7] ;
  args_info->no_incl_orig_help = gengetopt_args_info_help[8] ;
  args_info->seed_help = gengetopt_args_info_help[9] ;
  args_info->no_ambiguities_help = gengetopt_args_info_help[10] ;
  args_info->no_ambig_resolve_help = gengetopt_args_info_help[11] ;
  args_info->no_transprob_help = gengetopt_args_info_help[12] ;
  args_info->ambiguity_frequency_model_help = gengetopt_args_info_help[13] ;
  args_info->tstvratio_help = gengetopt_args_info_help[14] ;
  args_info->pyrtvratio_help = gengetopt_args_info_help[15] ;
  args_info->no_tstvratio_help = gengetopt_args_info_help[16] ;
  args_info->fixfactor_help = gengetopt_args_info_help[17] ;
  args_info->datasets_help = gengetopt_args_info_help[18] ;
  args_info->no_counts_help = gengetopt_args_info_help[20] ;
  args_info->method_help = gengetopt_args_info_help[21] ;
  args_info->method_min = -1;
  args_info->method_max = -1;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
    char *string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = NULL;
  new_node->orig = NULL;
}

static void
free_multiple_field(unsigned int len, void **arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->outfile_arg));
  free_string_field (&(args_info->outfile_orig));
  free_string_field (&(args_info->input_format_orig));
  free_string_field (&(args_info->output_format_orig));
  free_string_field (&(args_info->distance_function_orig));
  free_string_field (&(args_info->bootstraps_orig));
  free_string_field (&(args_info->seed_orig));
  free_string_field (&(args_info->ambiguity_frequency_model_orig));
  free_string_field (&(args_info->tstvratio_orig));
  free_string_field (&(args_info->pyrtvratio_orig));
  free_string_field (&(args_info->fixfactor_orig));
  free_string_field (&(args_info->datasets_orig));
  free_multiple_field (args_info->method_given, (void **)&(args_info->method_arg), &(args_info->method_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->outfile_given)
    write_into_file(outfile, "outfile", args_info->outfile_orig, 0);
  if (args_info->input_format_given)
    write_into_file(outfile, "input-format", args_info->input_format_orig, cmdline_parser_input_format_values);
  if (args_info->output_format_given)
    write_into_file(outfile, "output-format", args_info->output_format_orig, cmdline_parser_output_format_values);
  if (args_info->distance_function_given)
    write_into_file(outfile, "distance-function", args_info->distance_function_orig, cmdline_parser_distance_function_values);
  if (args_info->bootstraps_given)
    write_into_file(outfile, "bootstraps", args_info->bootstraps_orig, 0);
  if (args_info->no_incl_orig_given)
    write_into_file(outfile, "no-incl-orig", 0, 0 );
  if (args_info->seed_given)
    write_into_file(outfile, "seed", args_info->seed_orig, 0);
  if (args_info->no_ambiguities_given)
    write_into_file(outfile, "no-ambiguities", 0, 0 );
  if (args_info->no_ambig_resolve_given)
    write_into_file(outfile, "no-ambig-resolve", 0, 0 );
  if (args_info->no_transprob_given)
    write_into_file(outfile, "no-transprob", 0, 0 );
  if (args_info->ambiguity_frequency_model_given)
    write_into_file(outfile, "ambiguity-frequency-model", args_info->ambiguity_frequency_model_orig, cmdline_parser_ambiguity_frequency_model_values);
  if (args_info->tstvratio_given)
    write_into_file(outfile, "tstvratio", args_info->tstvratio_orig, 0);
  if (args_info->pyrtvratio_given)
    write_into_file(outfile, "pyrtvratio", args_info->pyrtvratio_orig, 0);
  if (args_info->no_tstvratio_given)
    write_into_file(outfile, "no-tstvratio", 0, 0 );
  if (args_info->fixfactor_given)
    write_into_file(outfile, "fixfactor", args_info->fixfactor_orig, 0);
  if (args_info->datasets_given)
    write_into_file(outfile, "datasets", args_info->datasets_orig, 0);
  if (args_info->no_counts_given)
    write_into_file(outfile, "no-counts", 0, 0 );
  write_multiple_into_file(outfile, args_info->method_given, "method", args_info->method_orig, cmdline_parser_method_values);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  char *tok, *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static char *
get_multiple_arg_token_next(const char *arg)
{
  char *tok;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc)
{
  int error = 0;

  if (option_given && ! (min < 0 && max < 0))
    {
      if (min >= 0 && max >= 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < min
              || option_given > max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min >= 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max >= 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->method_given, args_info->method_min, args_info->method_max, "'--method' ('-m')"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *multi_token, *multi_next; /* store single arguments */

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
    case ARG_ENUM:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_ENUM:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
      case ARG_ENUM:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = NULL;
      }
    }
  }
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * method_list = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "outfile",	1, NULL, 'o' },
        { "input-format",	1, NULL, 'I' },
        { "output-format",	1, NULL, 'O' },
        { "distance-function",	1, NULL, 'D' },
        { "bootstraps",	1, NULL, 'b' },
        { "no-incl-orig",	0, NULL, 'k' },
        { "seed",	1, NULL, 's' },
        { "no-ambiguities",	0, NULL, 'A' },
        { "no-ambig-resolve",	0, NULL, 'R' },
        { "no-transprob",	0, NULL, 't' },
        { "ambiguity-frequency-model",	1, NULL, 'a' },
        { "tstvratio",	1, NULL, 'T' },
        { "pyrtvratio",	1, NULL, 'P' },
        { "no-tstvratio",	0, NULL, 'N' },
        { "fixfactor",	1, NULL, 'F' },
        { "datasets",	1, NULL, 'd' },
        { "no-counts",	0, NULL, 'C' },
        { "method",	1, NULL, 'm' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVo:I:O:D:b:ks:ARta:T:P:NF:d:Cm:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'o':	/* output filename. If not specifed, output is written to stdout.  */
        
        
          if (update_arg( (void *)&(args_info->outfile_arg), 
               &(args_info->outfile_orig), &(args_info->outfile_given),
              &(local_args_info.outfile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "outfile", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'I':	/* input format.  */
        
        
          if (update_arg( (void *)&(args_info->input_format_arg), 
               &(args_info->input_format_orig), &(args_info->input_format_given),
              &(local_args_info.input_format_given), optarg, cmdline_parser_input_format_values, "phylip_multialignment", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "input-format", 'I',
              additional_error))
            goto failure;
        
          break;
        case 'O':	/* output format.  */
        
        
          if (update_arg( (void *)&(args_info->output_format_arg), 
               &(args_info->output_format_orig), &(args_info->output_format_given),
              &(local_args_info.output_format_given), optarg, cmdline_parser_output_format_values, "phylip_dm", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "output-format", 'O',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Distance function.  */
        
        
          if (update_arg( (void *)&(args_info->distance_function_arg), 
               &(args_info->distance_function_orig), &(args_info->distance_function_given),
              &(local_args_info.distance_function_given), optarg, cmdline_parser_distance_function_values, "K2P", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "distance-function", 'D',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Bootstrap num times and create matrix for each.  */
        
        
          if (update_arg( (void *)&(args_info->bootstraps_arg), 
               &(args_info->bootstraps_orig), &(args_info->bootstraps_given),
              &(local_args_info.bootstraps_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "bootstraps", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* If the distance matrix from the original sequences should be included.  */
        
        
          if (update_arg((void *)&(args_info->no_incl_orig_flag), 0, &(args_info->no_incl_orig_given),
              &(local_args_info.no_incl_orig_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-incl-orig", 'k',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Random seed. If not specified the current timestamp will be used.  */
        
        
          if (update_arg( (void *)&(args_info->seed_arg), 
               &(args_info->seed_orig), &(args_info->seed_given),
              &(local_args_info.seed_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "seed", 's',
              additional_error))
            goto failure;
        
          break;
        case 'A':	/* Ignore ambiguities.  */
        
        
          if (update_arg((void *)&(args_info->no_ambiguities_flag), 0, &(args_info->no_ambiguities_given),
              &(local_args_info.no_ambiguities_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-ambiguities", 'A',
              additional_error))
            goto failure;
        
          break;
        case 'R':	/* Specifies that ambigious symbols should not be resolved by nearest neighbor.  */
        
        
          if (update_arg((void *)&(args_info->no_ambig_resolve_flag), 0, &(args_info->no_ambig_resolve_given),
              &(local_args_info.no_ambig_resolve_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-ambig-resolve", 'R',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Specifies that the transition probabilities should not be used in the ambiguity model.  */
        
        
          if (update_arg((void *)&(args_info->no_transprob_flag), 0, &(args_info->no_transprob_given),
              &(local_args_info.no_transprob_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-transprob", 't',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Ambiguity frequency model.  */
        
        
          if (update_arg( (void *)&(args_info->ambiguity_frequency_model_arg), 
               &(args_info->ambiguity_frequency_model_orig), &(args_info->ambiguity_frequency_model_given),
              &(local_args_info.ambiguity_frequency_model_given), optarg, cmdline_parser_ambiguity_frequency_model_values, "UNI", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "ambiguity-frequency-model", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Transition/transvertion ratio for purine transitions ( for the TN model ).  */
        
        
          if (update_arg( (void *)&(args_info->tstvratio_arg), 
               &(args_info->tstvratio_orig), &(args_info->tstvratio_given),
              &(local_args_info.tstvratio_given), optarg, 0, "2.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "tstvratio", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* Transition/transvertion ratio for  pyrimidines transitions ( for the TN model ).  */
        
        
          if (update_arg( (void *)&(args_info->pyrtvratio_arg), 
               &(args_info->pyrtvratio_orig), &(args_info->pyrtvratio_given),
              &(local_args_info.pyrtvratio_given), optarg, 0, "2.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "pyrtvratio", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'N':	/* If given fixed ts/tv ratios will not be used.  */
        
        
          if (update_arg((void *)&(args_info->no_tstvratio_flag), 0, &(args_info->no_tstvratio_given),
              &(local_args_info.no_tstvratio_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-tstvratio", 'N',
              additional_error))
            goto failure;
        
          break;
        case 'F':	/* Float specifying what factor to use for saturated data. If not given -1 in the entry..  */
        
        
          if (update_arg( (void *)&(args_info->fixfactor_arg), 
               &(args_info->fixfactor_orig), &(args_info->fixfactor_given),
              &(local_args_info.fixfactor_given), optarg, 0, "1", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fixfactor", 'F',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* nr of datasets in input. Is used if the input format is clustalw.  */
        
        
          if (update_arg( (void *)&(args_info->datasets_arg), 
               &(args_info->datasets_orig), &(args_info->datasets_given),
              &(local_args_info.datasets_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "datasets", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* Tree file should not contain the counts.  */
        
        
          if (update_arg((void *)&(args_info->no_counts_flag), 0, &(args_info->no_counts_given),
              &(local_args_info.no_counts_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-counts", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* reconstruction method to apply.  */
        
          if (update_multiple_arg_temp(&method_list, 
              &(local_args_info.method_given), optarg, cmdline_parser_method_values, 0, ARG_ENUM,
              "method", 'm',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->method_arg),
    &(args_info->method_orig), args_info->method_given,
    local_args_info.method_given, 0 , 
    ARG_ENUM, method_list);

  args_info->method_given += local_args_info.method_given;
  local_args_info.method_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (method_list, 0 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
